# Generated by Django 3.2.7 on 2021-09-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20210919_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Корзину', 'verbose_name_plural': 'Корзина'},
        ),
    ]
