# Generated by Django 3.2.7 on 2021-09-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзыв'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
